title: Settings
data:
  site_name: 'Brittany Jones-Dumas'
  social:
    -
      name: Twitter
      url: 'https://twitter.com/justbritt_jd'
      icon: site/social-icons/twitter.svg
    -
      name: Github
      url: 'https://github.com/'
      icon: site/social-icons/github.svg
    -
      name: Email
      url: 'mailto:bajonesdumas@gmail.com'
      icon: site/social-icons/email.svg
